services:
  # ----------------------------------------
  # SERVICE 1: The Queue/Message Broker
  # ----------------------------------------
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:                 
      - ./redis_data:/data

  # ----------------------------------------
  # SERVICE 2: The API (Frontend facing)
  # ----------------------------------------
  api:
    build: . 
    container_name: moxcety-api
    extra_hosts:                               
      - "host.docker.internal:host-gateway"
    command: npx ts-node src/apps/api/server.ts 
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - SUPABASE_URL=http://192.168.1.15:54321
    volumes:               
      - ./src:/app/src

  # ----------------------------------------
  # SERVICE 3: The Fetch Worker
  # ----------------------------------------
  worker-fetch:
    build: .
    container_name: moxcety-fetch-worker
    command: npx ts-node src/apps/worker-fetch/index.ts 
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - SUPABASE_URL=http://192.168.1.15:54321
    volumes:               
      - ./src:/app/src
      - ./storage:/app/storage

  # ----------------------------------------
  # SERVICE 4: The Parse Worker
  # ----------------------------------------
  worker-parse:
    build: .
    container_name: moxcety-parse-worker
    extra_hosts:                                
      - "host.docker.internal:host-gateway"
    command: npx ts-node src/apps/worker-parse/index.ts 
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - SUPABASE_URL=http://192.168.1.15:54321
      - AI_URL=http://192.168.1.15:8000
    volumes:               
      - ./src:/app/src
      - ./storage:/app/storage