create table pages(
  id bigint generated by default as identity primary key,
  url text not null unique,
  title text,
  description text,
  body_text text,
  authority_score float default 1.0,
  last_crawled_at timestamp with time zone default timezone('utc'::text, now()),
  search_vector tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
    setweight(to_tsvector('english', left(coalesce(body_text, ''), 100000)), 'C')
  ) STORED
)