CREATE TABLE code_snippets (
  id bigint generated by default as identity primary key,
  page_id bigint references pages(id) on delete cascade,
  language text,
  content text,
  embedding vector(384) -- Matches our Python model (all-MiniLM-L6-v2)
);