
CREATE TABLE IF NOT EXISTS links (
  id bigint generated by default as identity primary key,
  from_id bigint references pages(id) on delete cascade not null,
  to_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique (from_id, to_url)
);


CREATE INDEX IF NOT EXISTS links_from_id_idx ON links(from_id);

CREATE INDEX IF NOT EXISTS links_to_url_idx ON links(to_url);